from typing import override, Optional

from ichatbio.agent import IChatBioAgent
from ichatbio.agent_response import ResponseContext, IChatBioAgentProcess
from ichatbio.server import build_agent_app
from ichatbio.types import AgentCard, AgentEntrypoint
from pydantic import BaseModel
from starlette.applications import Starlette


class HelloWorldAgent(IChatBioAgent):
    """
    A simple example agent with a single entrypoint.
    """

    @override
    def get_agent_card(self) -> AgentCard:
        return AgentCard(
            name="The Simplest Agent",
            description="Can only say \"Hello world!\".",
            icon="https://commons.wikimedia.org/wiki/Category:Hello_World#/media/File:Qt_example.png",
            url="http://localhost:9999",
            entrypoints=[
                AgentEntrypoint(
                    id="hello",
                    description="Responds with \"Hello world!\".",
                    parameters=None
                )
            ]
        )

    @override
    async def run(self, context: ResponseContext, request: str, entrypoint: str, params: Optional[BaseModel]):
        # Start a process to log the agent's actions
        async with context.begin_process(summary="Thinking") as process:
            process: IChatBioAgentProcess

            # Perform any long-running work in this process block, logging steps taken and their outcomes. iChatBio
            # users can see these log messages.
            await process.log("Hello world!")

            # Any results that should be identifiable should be packaged as an artifact. These may be online resources
            # like API responses, or offline data generated by the agent. Artifacts that exist online will automatically
            # be downloaded and versioned by iChatBio. Artifacts with new content will be hosted by iChatBio and made
            # available for users to download for some period of time.
            await process.create_artifact(
                mimetype="text/html",
                description="The Wikipedia page for \"Hello World\"",
                uris=["https://en.wikipedia.org/wiki/Hello_World"],
                metadata={"source": "Wikipedia"}
            )

        # Reply directly to the iChatBio agent, not the user
        await context.reply("I said it!")


def create_app() -> Starlette:
    agent = HelloWorldAgent()
    app = build_agent_app(agent)
    return app
